version: '3'

services:

  # test container service for holding test automation project and running the tests
  test_container:
    entrypoint: /bin/sh
    command: -c "./docker-resources/wait-for-grid.sh && ./docker-resources/wait_emulator_to_be_ready.sh && ./gradlew clean test" #wait for grid to be ready, then wait until emulators are up and running and then execute the tests
    image: framework_container
    container_name: test-container
    privileged: true
    volumes:
      - ./tests-output/testngOutput/:/docker_selenium_grid/tests-output/testngOutput/ #path to TestNG reports
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: "/docker_selenium_grid/"
    hostname: test_container_hostname
    networks:
      - docker_network
    depends_on:
      - selenium_hub
      - node_phone
      - node_tablet
    environment:
      - DOCKER_SELENIUM_PORT=4444
      - DOCKER_SELENIUM_HOST=selenium_hub
      - DOCKER_EMULATOR_PHONE=phone_container
      - DOCKER_EMULATOR_TABLET=tablet_container
    ports:
      - "8000:8000"

  # Selenium hub
  selenium_hub:
    image: selenium/hub:3.14.0-curium
    container_name: selenium-hub
    hostname: selenium-hub
    networks:
      - docker_network
    ports:
      - "4444:4444"

  # Service for Docker Android (Phone device)
  node_phone:
    image: budtmo/docker-android-x86-6.0
    container_name: phone_container
    privileged: true
    networks:
      - docker_network
    depends_on:
      - selenium_hub
    ports:
      - "6080:6080"
    volumes:
      - $PWD/docker-resources/utils.sh:/root/src/utils.sh
      - $PWD/docker-resources/supervisord.conf:/root/supervisord.conf
      - ./src/test/resources/TheApp-v1.8.0.apk:/root/apk/TheApp-v1.8.0.apk
      - ./tests-output/video/video-phone:/tmp/video # path to tests video execution
    environment:
      - DEVICE=Samsung Galaxy S6
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
      - MOBILE_WEB_TEST=false
      - AUTO_RECORD=true

  # Service for Docker Android (Tablet device)
  node_tablet:
    image: budtmo/docker-android-x86-12.0
    container_name: tablet_container
    privileged: true
    networks:
      - docker_network
    depends_on:
      - selenium_hub
    ports:
      - "6081:6080"
    volumes:
      - $PWD/docker-resources/utils.sh:/root/src/utils.sh
      - $PWD/docker-resources/supervisord.conf:/root/supervisord.conf
      - ./src/test/resources/TheApp-v1.8.0.apk:/root/apk/TheApp-v1.8.0.apk
      - ./tests-output/video/video-tablet:/tmp/video # path to tests video execution
    environment:
      - DEVICE=Nexus 10
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
      - MOBILE_WEB_TEST=false
      - AUTO_RECORD=true

networks:
  docker_network: