# This workflow build a docker image that contains Java with Gradle and run the android automated tests with docker-compose command 
name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build test_container docker image
        run: docker build -t test_container .
      
      - name: Run android UI tests
        run: docker-compose up -d 
