# This workflow build the docker image that contains Java with Gradle to store the testing framework
# and run the android automated tests with docker-compose command
name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    #container:
      #image:  docker:19.03.12
    steps:
      - uses: actions/checkout@v2

      #- name: Build docker image
        #run: docker build -t framework_container .
      - name: Installing KVM
        run: |
          sudo /usr/sbin/kvm-ok
          sudo apt-get install qemu-kvm libvirt-bin ubuntu-vm-builder bridge-utils
          sudo /usr/sbin/kvm-ok

      #- name: Run Android Samsung Galaxy S6
        #run: docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Samsung Galaxy S6" --name samsung_s6_container budtmo/docker-android-x86-6.0

      #- name: Run Android Samsung Galaxy S10
        #run: docker run --privileged -d -p 6081:6080 -p 5552:5552 -p 5553:5553 -e DEVICE="Samsung Galaxy S10" --name samsung_s10_container budtmo/docker-android-x86-8.0

      - name: Run Android with Google Emulator
        run: docker run -e ADBKEY="$(cat ~/.android/adbkey)" --device /dev/kvm --publish 8554:8554/tcp --publish 5555:5555/tcp  --name google_emulator us-docker.pkg.dev/android-emulator-268719/images/30-google-x64:30.1.2

      - name: Check android emulators
        run: ./docker-resources/check_emulator_container.sh
        #- name: Run android UI tests
          #run: docker-compose up test_container

      #- name: Install docker-compose
          #run: |
          #apk add --no-cache docker-compose
        #docker-compose --version
      
      #- name: Run android UI tests
        #run: docker-compose up
              
        #if: ${{ always() }}
        #- name: Archive tests results
        #uses: actions/upload-artifact@v2
          #with:
        #path: tests-output/
