# This workflow build the docker image that contains Java with Gradle to store the testing framework
# and run the android automated tests with docker-compose command
name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  docker:19.03.12
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t framework_container .
      
      - name: Run android UI tests
        run: docker-compose up 
